language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-18
    - python: 2.7
      env: TOXENV=py27-19
    - python: 2.7
      env: TOXENV=py27-110
    - python: 2.7
      env: TOXENV=py27-111
    - python: 3.3
      env: TOXENV=py33-18
    - python: 3.4
      env: TOXENV=py34-18
    - python: 3.4
      env: TOXENV=py34-19
    - python: 3.4
      env: TOXENV=py34-110
    - python: 3.4
      env: TOXENV=py34-111
    - python: 3.4
      env: TOXENV=py34-20
    - python: 3.5
      env: TOXENV=py35-18
    - python: 3.5
      env: TOXENV=py35-19
    - python: 3.5
      env: TOXENV=py35-110
    - python: 3.5
      env: TOXENV=py35-111
    - python: 3.5
      env: TOXENV=py35-20
    - python: 3.6
      env: TOXENV=py36-111
    - python: 3.6
      env: TOXENV=py36-20
install:
  - pip install tox
script:
  - tox -e $TOXENV
